name: Testing workflow

on: push

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .
  test:
    needs: style_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install requirements"
        run: pip install -r requirements.txt
      - name: "Run pytest and collect coverage"
        run: coverage run -m pytest
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: .coverage
          path: .coverage
          retention-days: 1
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Download a single artifact"
        uses: actions/download-artifact@v2
        with:
          name: .coverage
      - name: "Install coverage"
        run: pip install coverage
      - name: "Create coverage report"
        run: coverage report
      - name: "Create XML"
        run: coverage xml
      - name: "Upload XML file"
        uses: actions/upload-artifact@v2
        with:
          name: coverage.xml
          path: coverage.xml
          retention-days: 14
